spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: 391738
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: PRODUCT-SERVER
  config:
    import: optional:configserver:http://localhost:8888
    eureka:
         instance:
           client:
             serverUrl:
               defaultZone: http://localhost:8761/eureka/
  cloud:
      server:
        git:
          uri: https://github.com/Earbunsong/config-server2/
          clone-on-start: true
          default-label: main
